apiVersion: v1
kind: Service
metadata:
  name: framingo-example
  labels:
    app: framingo-example
spec:
  type: ClusterIP
  selector:
    app: framingo-example
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: pprof
    port: 6060
    targetPort: 6060
    protocol: TCP
